
services:
  devponcet07clientweb:
    build: 
      context: ./devponcet07_client_web
    working_dir: /app
    container_name: devponcet07ClientWeb
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - proxy-network
    expose:
      - "3000"

networks:
  proxy-network:
    external: true